api:
  image: alebarrionovo/pedelogo-catalogo:v1.0.0
  serviceType: NodePort

mongodb:
  tag: 4.2.8
  #existSecret: nome do secret
  credentials:
    userName: mongouser
    userPassword: mongopwd
  databaseName: admin